# Site settings
title: site title
email: your-email@domain.com
description: "site description"
encoding: utf-8
baseurl: "/science-of-future"
url: "/"

# Build settings
markdown: rdiscount
permalink: pretty
# permalink: /:categories/:title
extensions: [fenced_code_blocks]
collections:
 reports:
  output: true 
 reports_youth:
  output: true
 sections:
  output: true
 sections_youth:
  output: true
 organizations:
  output: true
 organizations_youth:
  output: true
